### ISSUE TITLE
Can you review the pull request?

### ISSUE THREAD

**Issue by jianxu305** [BlankerL/DXY-COVID-19-Data#10]
I am trying to put in some analysis codes into the project.  Can you please review the pull request?

If you feel ok to merge that into master, then I can directly contribute to this project this way.  Please let me know if you have any concerns.  Thanks.

**Comment by BlankerL** [comment]
Sure. I was busy for the last two days so I cannot check your pull request in time.

I might check the pull request this evening because I cannot read the Jupyter Notebook file directly on GitHub, and I do not have a Jupyter install on the machine. 

By the way, I opened this project just for data storage. If you have an idea on analyzing them, you can open a project on you own. I can add a referenece to your project in the README file.

**Comment by jianxu305** [comment]
Thanks.  Then let me open another project for analysis, and use your data.
