### ISSUE TITLE
failure in db connection

### ISSUE THREAD

**Issue by 494612231** [BlankerL/DXY-COVID-19-Data#3]
Fail to connect to your database, an error comes with "getaddrinfo failed", which I think might due to aninproper URI? Your kind help is very much appreciated!

**Comment by BlankerL** [comment]
Hello, 

The script is just showing how the data are processed and saved into csv files. The database itself is not public to everyone because my MongoDB cannot maintain more than 100 connections at the same time. 

If you eagerly want to get the raw data, please use the API: https://lab.isaaclin.cn/nCoV/ and get the JSON-formatted data, with which you will be able to preprocess and get the result on your own. 

Furthermore, with the [crawler project](https://github.com/BlankerL/DXY-2019-nCov-Crawler), you will be able to easily build your own database and use your own MONGO_URI.

**Comment by 494612231** [comment]
> Hello,
> 
> The script is just showing how the data are processed and saved into csv files. The database itself is not public to everyone because my MongoDB cannot maintain more than 100 connections at the same time.
> 
> If you eagerly want to get the raw data, please use the API: https://lab.isaaclin.cn/nCoV/ and get the JSON-formatted data, with which you will be able to preprocess and get the result on your own.
> 
> Furthermore, with the [crawler project](https://github.com/BlankerL/DXY-2019-nCov-Crawler), you will be able to easily build your own database and use your own MONGO_URI.

**Comment by 494612231** [comment]
Noted and thanks~
