### ISSUE TITLE
suggest modify the English name of 陕西 to shaanxi

### ISSUE THREAD

**Issue by l1t1** [BlankerL/DXY-COVID-19-Data#31]
so that it can distinguish  the English name of 山西
see http://www.stats.gov.cn/tjsj/ndsj/2019/indexeh.htm

**Comment by l1t1** [comment]
also suggest  add a column of area code 
http://www.mca.gov.cn/article/sj/xzqh/2019/

**Comment by BlankerL** [comment]
Thank you for your advice, I have changed the English name of 陕西 to Shaanxi.

The `locationId` is provided by Ding Xiang Yuan. In mainland China, the `locationId` is the zip code of  cities. 

JSON files contain this field, but CSV files do not. Simply because Ding Xiang Yuan does not provide the `locationId` for all cities. For example, the `locationId` for some cities like 大理 (Dali City, Yunnan Province) is not provided. 

As requested, I have add this field in CSV files, but some of them are missing. 

Thank you for the provided version of area code, I might apply them to all cities once I am free, but, actually, the names of cities in your URL does not match most of the Ding Xiang Yuan provided city names, there are always about 1 or 2 characters difference, so it will be a quite tricky job.
