### ISSUE TITLE
Many garbled code in DXYAreas.json

### ISSUE THREAD

**Issue by denven** [BlankerL/DXY-COVID-19-Data#45]
And some data are mixed and unvalid, like: 

Just search 'Bhutan' to take a look, there are 3 results

**Comment by BlankerL** [comment]
Thanks, I will check it right now.

**Comment by BlankerL** [comment]
Thanks a lot, I have already fixed it. 

I suppose this error happens because the gunicorn backend cannot handle so many connections at the same time, and the return documents contain missing and/or duplicated characters at this time. 

However, I have no idea why the unstructured data will be pushed onto GitHub because all the content should go through `json.dump()`, but at least we fixed it and let's see what is going on.
